CREATE TABLE `Facet_EvernoteNote` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `USN` int(11) DEFAULT NULL,
  `guid` varchar(127) DEFAULT NULL,
  `active` bit(1) DEFAULT NULL,
  `altitude` double DEFAULT NULL,
  `author` longtext,
  `content` longtext,
  `contentClass` varchar(255) DEFAULT NULL,
  `contentHash` tinyblob,
  `contentLength` int(11) DEFAULT NULL,
  `created` bigint(20) DEFAULT NULL,
  `creatorId` int(11) DEFAULT NULL,
  `deleted` bigint(20) DEFAULT NULL,
  `htmlContent` longtext,
  `lastEditedBy` longtext,
  `tagGuidsStorage` longtext,
  `lastEditorId` int(11) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `notebookGuid` varchar(255) DEFAULT NULL,
  `placeName` longtext,
  `reminderDoneTime` bigint(20) DEFAULT NULL,
  `reminderOrder` bigint(20) DEFAULT NULL,
  `reminderTime` bigint(20) DEFAULT NULL,
  `shareDate` bigint(20) DEFAULT NULL,
  `source` longtext,
  `sourceApplication` longtext,
  `sourceURL` longtext,
  `subjectDate` bigint(20) DEFAULT NULL,
  `title` longtext,
  `updated` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `guid` (`guid`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_EvernoteNotebook` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `guid` varchar(127) NULL,
  `USN` int(11) NULL,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `defaultNotebook` bit(1) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `published` bit(1) DEFAULT NULL,
  `publishing` tinyblob,
  `serviceCreated` bigint(20) DEFAULT NULL,
  `serviceUpdated` bigint(20) DEFAULT NULL,
  `stack` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `guid` (`guid`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_EvernoteTag` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `guid` varchar(127) NULL,
  `USN` int(11) NULL,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `guid` (`guid`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_EvernoteResource` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `USN` int(11) DEFAULT NULL,
  `guid` varchar(127) DEFAULT NULL,
  `alternateDataBodyHash` tinyblob,
  `alternateDataSize` int(11) DEFAULT NULL,
  `altitude` double DEFAULT NULL,
  `cameraMake` varchar(255) DEFAULT NULL,
  `cameraModel` varchar(255) DEFAULT NULL,
  `dataBodyHash` tinyblob,
  `dataSize` int(11) DEFAULT NULL,
  `fileName` varchar(255) DEFAULT NULL,
  `height` smallint(6) DEFAULT NULL,
  `isAttachment` bit(1) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `mime` varchar(255) DEFAULT NULL,
  `noteGuid` varchar(127) DEFAULT NULL,
  `recoType` varchar(255) DEFAULT NULL,
  `recognitionDataBodyHash` tinyblob,
  `recognitionDataSize` int(11) DEFAULT NULL,
  `sourceURL` varchar(255) DEFAULT NULL,
  `timestamp` bigint(20) DEFAULT NULL,
  `width` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `guid` (`guid`),
  KEY `noteGuid` (`noteGuid`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_EvernotePhoto` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `USN` int(11) DEFAULT NULL,
  `guid` varchar(255) DEFAULT NULL,
  `resourceFacet_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK3645693AFCFC4763` (`resourceFacet_id`),
  KEY `guid` (`guid`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;