CREATE TABLE `Facet_GoogleCalendarEvent` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `attendeesStorage` longtext,
  `calendarId` varchar(255) DEFAULT NULL,
  `colorId` longtext,
  `created` bigint(20) NOT NULL,
  `eventUpdated` bigint(20) NOT NULL,
  `creatorStorage` longtext,
  `description` longtext,
  `endTimeUnspecified` bit(1) DEFAULT NULL,
  `endTimezoneShift` int(11) NOT NULL,
  `etag` longtext,
  `googleId` varchar(255) DEFAULT NULL,
  `guestsCanSeeOtherGuests` bit(1) DEFAULT NULL,
  `hangoutLink` longtext,
  `htmlLink` longtext,
  `iCalUID` longtext,
  `kind` longtext,
  `location` longtext,
  `locked` bit(1) DEFAULT NULL,
  `organizerStorage` longtext,
  `originalStartTime` bigint(20) NOT NULL,
  `recurrence` longtext,
  `recurringEventId` varchar(255) DEFAULT NULL,
  `sequence` int(11) DEFAULT NULL,
  `startTimezoneShift` int(11) NOT NULL,
  `status` longtext,
  `summary` longtext,
  `transparency` varchar(255) DEFAULT NULL,
  `visibility` varchar(255) DEFAULT NULL,
  `allDayEvent` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `update_index` (`eventUpdated`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `googleId` (`googleId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;