CREATE TABLE `Facet_FitbitFoodLogEntry` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `endTimeStorage` varchar(255) DEFAULT NULL,
  `startTimeStorage` varchar(255) DEFAULT NULL,
  `NV_Calories` float NOT NULL,
  `NV_Carbs` float NOT NULL,
  `NV_Fat` float NOT NULL,
  `NV_Fiber` float NOT NULL,
  `NV_Protein` float NOT NULL,
  `NV_Sodium` float NOT NULL,
  `accessLevel` varchar(255) DEFAULT NULL,
  `amount` float NOT NULL,
  `brand` varchar(255) DEFAULT NULL,
  `calories` int(11) NOT NULL,
  `foodId` bigint(20) NOT NULL,
  `isFavorite` bit(1) NOT NULL,
  `locale` varchar(255) DEFAULT NULL,
  `logId` bigint(20) NOT NULL,
  `mealTypeId` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `unitId` int(11) NOT NULL,
  `unitName` varchar(255) DEFAULT NULL,
  `unitPlural` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_FitbitFoodLogSummary` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `endTimeStorage` varchar(255) DEFAULT NULL,
  `startTimeStorage` varchar(255) DEFAULT NULL,
  `calories` float NOT NULL,
  `caloriesGoal` int(11) NOT NULL,
  `caloriesOutGoal` int(11) NOT NULL,
  `carbs` float NOT NULL,
  `fat` float NOT NULL,
  `fiber` float NOT NULL,
  `protein` float NOT NULL,
  `sodium` float NOT NULL,
  `water` float NOT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
