CREATE TABLE `Facet_JawboneUpMeal` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `time_completed` bigint(20) DEFAULT NULL,
  `time_created` bigint(20) DEFAULT NULL,
  `time_updated` bigint(20) DEFAULT NULL,
  `tz` varchar(255) DEFAULT NULL,
  `xid` varchar(255) DEFAULT NULL,
  `place_acc` int(11) DEFAULT NULL,
  `place_lat` double DEFAULT NULL,
  `place_lon` double DEFAULT NULL,
  `place_name` varchar(255) DEFAULT NULL,
  `mealDetails` longtext,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `xid` (`xid`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_JawboneUpServing` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `time_completed` bigint(20) DEFAULT NULL,
  `time_created` bigint(20) DEFAULT NULL,
  `time_updated` bigint(20) DEFAULT NULL,
  `tz` varchar(255) DEFAULT NULL,
  `xid` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `servingDetails` longtext,
  `meal_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKC04FA357372A348` (`meal_id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `xid` (`xid`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`),
  CONSTRAINT `FKC04FA357372A348` FOREIGN KEY (`meal_id`) REFERENCES `Facet_JawboneUpMeal` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_JawboneUpSleep` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `time_completed` bigint(20) DEFAULT NULL,
  `time_created` bigint(20) DEFAULT NULL,
  `time_updated` bigint(20) DEFAULT NULL,
  `tz` varchar(255) DEFAULT NULL,
  `xid` varchar(255) DEFAULT NULL,
  `place_acc` int(11) DEFAULT NULL,
  `place_lat` double DEFAULT NULL,
  `place_lon` double DEFAULT NULL,
  `place_name` varchar(255) DEFAULT NULL,
  `asleep_time` bigint(20) NOT NULL,
  `awake` int(11) NOT NULL,
  `awake_time` bigint(20) NOT NULL,
  `awakenings` int(11) NOT NULL,
  `deep` int(11) NOT NULL,
  `duration` int(11) NOT NULL,
  `light` int(11) NOT NULL,
  `phasesStorage` longtext,
  `quality` int(11) NOT NULL,
  `rem` int(11) NOT NULL,
  `smart_alarm_fire` bigint(20) NOT NULL,
  `snapshot_image` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `xid` (`xid`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_JawboneUpMoves` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `time_completed` bigint(20) DEFAULT NULL,
  `time_created` bigint(20) DEFAULT NULL,
  `time_updated` bigint(20) DEFAULT NULL,
  `tz` varchar(255) DEFAULT NULL,
  `xid` varchar(255) DEFAULT NULL,
  `active_time` int(11) NOT NULL,
  `bg_calories` double NOT NULL,
  `bmr` double NOT NULL,
  `bmr_day` double NOT NULL,
  `calories` double NOT NULL,
  `distance` int(11) NOT NULL,
  `inactive_time` int(11) NOT NULL,
  `intensityStorage` longtext,
  `km` double NOT NULL,
  `longest_active` int(11) NOT NULL,
  `longest_idle` int(11) NOT NULL,
  `snapshot_image` varchar(255) DEFAULT NULL,
  `steps` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `tzs` varchar(255) DEFAULT NULL,
  `wo_active_time` int(11) NOT NULL,
  `wo_calories` double NOT NULL,
  `wo_count` int(11) NOT NULL,
  `wo_longest` int(11) NOT NULL,
  `wo_time` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `xid` (`xid`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Facet_JawboneUpWorkout` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `time_completed` bigint(20) DEFAULT NULL,
  `time_created` bigint(20) DEFAULT NULL,
  `time_updated` bigint(20) DEFAULT NULL,
  `tz` varchar(255) DEFAULT NULL,
  `xid` varchar(255) DEFAULT NULL,
  `place_acc` int(11) DEFAULT NULL,
  `place_lat` double DEFAULT NULL,
  `place_lon` double DEFAULT NULL,
  `place_name` varchar(255) DEFAULT NULL,
  `bg_active_time` int(11) DEFAULT NULL,
  `bg_calories` double DEFAULT NULL,
  `bmr` double DEFAULT NULL,
  `bmr_calories` double DEFAULT NULL,
  `calories` double DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `intensity` int(11) DEFAULT NULL,
  `km` double DEFAULT NULL,
  `meters` double DEFAULT NULL,
  `route` varchar(255) DEFAULT NULL,
  `snapshot_image` varchar(255) DEFAULT NULL,
  `steps` int(11) DEFAULT NULL,
  `sub_type` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `workoutDetails` longtext,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `xid` (`xid`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `date` (`date`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JawboneUpMovesHourlyTotals` (
  `MovesRecordID` bigint(20) NOT NULL,
  `active_time` int(11) DEFAULT NULL,
  `calories` double DEFAULT NULL,
  `distance` int(11) DEFAULT NULL,
  `inactive_time` int(11) DEFAULT NULL,
  `longest_active_time` int(11) DEFAULT NULL,
  `longest_idle_time` int(11) DEFAULT NULL,
  `start` bigint(20) NOT NULL,
  `steps` int(11) DEFAULT NULL,
  KEY `FK2144A2A3AFFC9926` (`MovesRecordID`),
  CONSTRAINT `FK2144A2A3AFFC9926` FOREIGN KEY (`MovesRecordID`) REFERENCES `Facet_JawboneUpMoves` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
