CREATE TABLE `Facet_BedditSleep` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `comment` longtext,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `tags` longtext,
  `timeUpdated` bigint(20) NOT NULL,
  `awayCount` int(11) NOT NULL,
  `heartRateCurveData` longtext,
  `respirationRate` double DEFAULT NULL,
  `restingHeartRate` double NOT NULL,
  `scoreAwakenings` double NOT NULL,
  `scoreBedExits` double NOT NULL,
  `scoreFallAsleepTime` double NOT NULL,
  `scoreSleepAmount` double NOT NULL,
  `scoreSleepEfficiency` double NOT NULL,
  `scoreSnoring` double NOT NULL,
  `sleepCyclesData` longtext,
  `sleepStagesData` longtext,
  `sleepTags` longtext,
  `sleepTimeTarget` double NOT NULL,
  `snoringAmount` double NOT NULL,
  `snoringEpisodesData` longtext,
  `timeToFallAsleep` double DEFAULT NULL,
  `totalAwayTime` double NOT NULL,
  `totalSleepTime` double NOT NULL,
  `totalTimeNoSignal` double NOT NULL,
  `totalWakeTime` double NOT NULL,
  `updatedTime` double NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `apiKey` (`apiKeyId`),
  KEY `timeUpdated_index` (`timeUpdated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
