ALTER TABLE MovesMoveActivity ADD COLUMN activityGroup VARCHAR(255) NULL;
ALTER TABLE MovesPlaceActivity ADD COLUMN activityGroup VARCHAR(255) NULL;
ALTER TABLE MovesMoveActivity ADD COLUMN manual bit(1) NOT NULL default false;
ALTER TABLE MovesPlaceActivity ADD COLUMN manual bit(1) NOT NULL default false;
ALTER TABLE MovesMoveActivity ADD COLUMN duration int(11) NULL;
ALTER TABLE MovesPlaceActivity ADD COLUMN duration int(11) NULL;
UPDATE MovesPlaceActivity SET activityGroup="transport" WHERE activity="trp";
UPDATE MovesPlaceActivity SET activityGroup="cycling" WHERE activity="cyc";
UPDATE MovesPlaceActivity SET activityGroup="running" WHERE activity="run";
UPDATE MovesPlaceActivity SET activityGroup="walking" WHERE activity="wlk";
UPDATE MovesMoveActivity SET activityGroup="transport" WHERE activity="trp";
UPDATE MovesMoveActivity SET activityGroup="cycling" WHERE activity="cyc";
UPDATE MovesMoveActivity SET activityGroup="running" WHERE activity="run";
UPDATE MovesMoveActivity SET activityGroup="walking" WHERE activity="wlk";
UPDATE MovesPlaceActivity SET activity="transport" WHERE activity="trp";
UPDATE MovesPlaceActivity SET activity="cycling" WHERE activity="cyc";
UPDATE MovesPlaceActivity SET activity="running" WHERE activity="run";
UPDATE MovesPlaceActivity SET activity="walking" WHERE activity="wlk";
UPDATE MovesMoveActivity SET activity="transport" WHERE activity="trp";
UPDATE MovesMoveActivity SET activity="cycling" WHERE activity="cyc";
UPDATE MovesMoveActivity SET activity="running" WHERE activity="run";
UPDATE MovesMoveActivity SET activity="walking" WHERE activity="wlk";
