ALTER TABLE `Facet_VisitedCity` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_BodymediaBurn` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_BodymediaSleep` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_FitbitActivity` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_FitbitLoggedActivity` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_FitbitSleep` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_FitbitWeight` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_FlickrPhoto` ADD INDEX `date` (`date`);
ALTER TABLE `Facet_ZeoSleepStats` ADD INDEX `date` (`date`);
