CREATE TABLE `Facet_WithingsActivity` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `api` int(11) NOT NULL,
  `comment` longtext COLLATE utf8mb4_unicode_ci,
  `end` bigint(20) NOT NULL,
  `fullTextDescription` longtext COLLATE utf8mb4_unicode_ci,
  `guestId` bigint(20) NOT NULL,
  `isEmpty` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `objectType` int(11) NOT NULL,
  `start` bigint(20) NOT NULL,
  `timeUpdated` bigint(20) NOT NULL,
  `date` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `timezone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tags` longtext COLLATE utf8mb4_unicode_ci,
  `apiKeyId` bigint(20) DEFAULT NULL,
  `startTimeStorage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `endTimeStorage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `steps` int(11) NOT NULL,
  `distance` float NOT NULL,
  `calories` float NOT NULL,
  `elevation` float NOT NULL,
  PRIMARY KEY (`id`),
  KEY `isEmpty_index` (`isEmpty`),
  KEY `end_index` (`end`),
  KEY `start_index` (`start`),
  KEY `api_index` (`api`),
  KEY `objectType_index` (`objectType`),
  KEY `guestId_index` (`guestId`),
  KEY `timeUpdated_index` (`timeUpdated`),
  KEY `apiKey` (`apiKeyId`),
  KEY `date` (`date`(250))
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
